# Simple workflow for deploying static content to GitHub Pages
name: Generate schedules and deploy content to Pages

on:
  schedule:
    - cron: '0 0 */1 * *'
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  get_schedules:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        node-version: 18
    
    - run: npm install
    - run: npm run build
    - uses: EndBug/add-and-commit@v9
      with:
        author_name: 'Data Updater'
        message: 'Update schedules'
        add: '/*'
        remove: ''
        cwd: 'docs/data/'
        pull: '--rebase --autostash'
  # Build job
  build:
    runs-on: ubuntu-latest
    needs: get_schedules
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: 'docs/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
