name: Generate schedules and commit changes

on:
  schedule:
    - cron: '30 2,5 */1 * *'
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  get_schedules:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 22
      uses: actions/setup-node@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        node-version: 22
    
    - run: npm ci

    - run: npm run build

    - run: npm run test
    - uses: EndBug/add-and-commit@v9
      with:
        message: 'Update schedules'
        add: '*'
        remove: ''
        cwd: 'data/'
        pull: '--rebase --autostash'
        author_name: 'github-actions[bot]'
        author_email: 'bot@github.com'
